# Generated by Django 3.1.6 on 2021-02-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_auto_20210217_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileimages',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('propic', models.ImageField(blank=True, upload_to='profile_pic')),
            ],
        ),
    ]
