# Generated by Django 3.1.6 on 2021-02-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profileimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_img',
        ),
    ]
