# Generated by Django 3.1.6 on 2021-03-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210307_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='propic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic'),
        ),
    ]
