# Generated by Django 3.1.6 on 2021-03-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210328_1415'),
    ]

    operations = [
       
    ]
