# Generated by Django 3.1.6 on 2021-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userinfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
