# Generated by Django 3.1.6 on 2021-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userinfo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cover',
            field=models.ImageField(blank=True, default='defaultcover.png', upload_to='cover_photo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='propic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic'),
        ),
    ]
