# Generated by Django 3.1.6 on 2021-03-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, default='defaultpost.jpg', upload_to='postimages'),
        ),
    ]
