# Generated by Django 3.1.6 on 2021-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSocialClub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='msg_content',
            field=models.TextField(blank=True),
        ),
    ]
