# Generated by Django 3.1.6 on 2021-05-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheSocialClub', '0002_auto_20210506_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ['-created_at']},
        ),
    ]
